//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyKhachSanEntities : DbContext
    {
        public QuanLyKhachSanEntities()
            : base("name=QuanLyKhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhapKho> PhieuNhapKhoes { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<v_BaoCaoDoanhThuNangCao> v_BaoCaoDoanhThuNangCao { get; set; }
        public virtual DbSet<v_HoaDon_DaThanhToan> v_HoaDon_DaThanhToan { get; set; }
    
        public virtual int sp_CheckIn(Nullable<int> maPhong, Nullable<int> maKH, Nullable<int> maNV)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(int));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CheckIn", maPhongParameter, maKHParameter, maNVParameter);
        }
    
        public virtual int sp_DangKy(string hoTen, string taiKhoan, string matKhau)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKy", hoTenParameter, taiKhoanParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string taiKhoan, string matKhau)
        {
            var taiKhoanParameter = taiKhoan != null ?
                new ObjectParameter("TaiKhoan", taiKhoan) :
                new ObjectParameter("TaiKhoan", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", taiKhoanParameter, matKhauParameter);
        }
    
        public virtual int sp_DoiPhong(Nullable<int> maHD, Nullable<int> maPhongMoi)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            var maPhongMoiParameter = maPhongMoi.HasValue ?
                new ObjectParameter("MaPhongMoi", maPhongMoi) :
                new ObjectParameter("MaPhongMoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiPhong", maHDParameter, maPhongMoiParameter);
        }
    
        public virtual ObjectResult<sp_PhongTrong_Result> sp_PhongTrong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PhongTrong_Result>("sp_PhongTrong");
        }
    
        public virtual ObjectResult<sp_TimKhachHang_Result> sp_TimKhachHang(string cCCD)
        {
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKhachHang_Result>("sp_TimKhachHang", cCCDParameter);
        }
    
        public virtual int sp_ThanhToan(Nullable<int> maHD)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToan", maHDParameter);
        }
    
        public virtual int sp_ThemDichVu(Nullable<int> maHD, Nullable<int> maDV, Nullable<int> soLuong)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            var maDVParameter = maDV.HasValue ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDichVu", maHDParameter, maDVParameter, soLuongParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDoanhThu_Result> sp_ThongKeDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDoanhThu_Result>("sp_ThongKeDoanhThu", tuNgayParameter, denNgayParameter);
        }
    }
}
