//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BaoCaoDoanhThuNangCao
    {
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<System.DateTime> NgayCheckOut { get; set; }
        public string TenKhachHang { get; set; }
        public string TenPhong { get; set; }
        public string TenLoai { get; set; }
        public string TenNhanVien { get; set; }
        public decimal TienPhong { get; set; }
        public decimal TienDichVu { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<System.DateTime> NgayCheckIn { get; set; }
    }
}
