//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_HoaDon_DaThanhToan
    {
        public int MaHD { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayCheckIn { get; set; }
        public Nullable<System.DateTime> NgayCheckOut { get; set; }
        public Nullable<decimal> TienPhong { get; set; }
        public Nullable<decimal> TienDichVu { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> TrangThaiThanhToan { get; set; }
    }
}
